service: sparcs-events-api
frameworkVersion: ^3.25.0

custom:
  projectName: sparcs-events
  serviceName: events
  stage: ${opt:stage, self:provider.stage}
  entities: ${self:custom.stage}-${self:custom.projectName}-entities
  events: ${self:custom.stage}-${self:custom.projectName}
  bucket: ${self:custom.stage}-${self:custom.projectName}-file-bucket
  registrations: ${self:custom.stage}-${self:custom.projectName}-registrations
  preregistrations: ${self:custom.stage}-${self:custom.projectName}-preregistrations
  evaluations: ${self:custom.stage}-${self:custom.projectName}-evaluations
  frontendUrl: https://techtix.app
  konfHubApiKey: ${ssm:/konfhub/api-key-${self:custom.stage}}
  emailQueue:
    !ImportValue EmailQueue-${self:custom.stage}
  certificateQueue:
    !ImportValue CertificateQueue-${self:custom.stage}
  basicAuthorizerARN:
    !ImportValue BasicAuthAuthorizerARN-${self:custom.stage}
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy:
      - requests
      - boto3
      - botocore
    layer:
      name: sparcs-events-${self:custom.stage}-python-requirements
      compatibleRuntimes:
        - python3.8
    slim: true

package: ${file(resources/package.yml)}

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  memorySize: 3008
  versionFunctions: false
  timeout: 30
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Action: execute-api:Invoke
        Principal: "*"
        Resource: execute-api:/*/*/*
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:custom.stage}
    FRONTEND_URL: ${self:custom.frontendUrl}
    ENTITIES_TABLE: ${self:custom.entities}
    REGISTRATIONS_TABLE: ${self:custom.registrations}
    PREREGISTRATIONS_TABLE: ${self:custom.preregistrations}
    EVALUATIONS_TABLE: ${self:custom.evaluations}
    EVENTS_TABLE: ${self:custom.events}
    EMAIL_QUEUE: ${self:custom.emailQueue}
    CERTIFICATE_QUEUE: ${self:custom.certificateQueue}
    S3_BUCKET: ${self:custom.bucket}
    KONFHUB_API_KEY: ${self:custom.konfHubApiKey}
    USER_POOL_ID:
      !ImportValue UserPoolId-${self:custom.stage}
    USER_POOL_CLIENT_ID:
      !ImportValue AppClientId-${self:custom.stage}
    SPARCS_GMAIL: sparcsup@gmail.com
  logs:
    restApi: true

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/api_gateway.yml)}
  - ${file(resources/s3.yml)}

functions:
  - ${file(resources/api.yml)}
  # - ${file(resources/functions.yml)}

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
