patterns:
  - "setup/**"
  - "src/**"
  - "!requirements.txt"
  - "!.serverless/**"
  - "!venv/**"
  - "!node_modules/**"
  - "!.idea/**"
  - "!node_modules**"
  - "!package.json"
  - "!package-lock.json"
  - "!Pipfile"
  - "!Pipfile.lock"
  - "!log.txt"
  - "!README.md"
  - "!ruff.toml"
  - "!scripts/**"
  - "!resources/**"
  - "!__pycache__/**"
